### ISSUE TITLE
Is anyway you could get groups from Keycloak in ssh config?

### ISSUE THREAD

**Issue by einar-lanfranco** [please-openit/oauth2-ops-webinaire#1]

**Comment by please-openit** [comment]
You can not get groups directly. You have to create (or use an existing) scope that will add groups in user info and access_token. The "microprofile-jwt" scope has the mapper you need.
Then, you have to add a rule in the pam-exec-oauth2/main.go file https://github.com/shimt/pam-exec-oauth2/blob/master/main.go#L119 to add a filter on a user property.

**Comment by einar-lanfranco** [comment]
Thanks for the quick reponse ! Im working in this way!
